quad matrices
LevonKhazhoyan/hometasks pull request #10
Opened 2021-03-12 11:38 UTC by LevonKhazhoyan

2021-03-16 11:29 UTC, gsvgit requested changes

2021-03-16 11:29 UTC, gsvgit commented on src/hometask8/Main.fs
> +[<EntryPoint>]
Ой, а что это за файл такой?

2021-03-16 11:29 UTC, gsvgit commented on src/hometask8/QuadTree.fs
> +                    if sum1 = None && sum2 = None && sum3 = None && sum4 = None then None
Правда ли, что вот эту "чистку" нельзя вынести в отдельную функцию? Она у Вас в енскольких местах повторяется.

2021-03-16 11:29 UTC, gsvgit commented on tests/hometask8Tests/hometask8Tests.fs
> +
А где простое умноденеи деревьев квадрантов? Думается, надо больше крайних случаев. Напрмиер, провеить, что деревья действительно чистятся.

2021-03-18 22:26 UTC, LevonKhazhoyan commented on src/hometask8/Main.fs
> +[<EntryPoint>]
Удалил

2021-03-18 22:26 UTC, LevonKhazhoyan commented on src/hometask8/QuadTree.fs
> +                    if sum1 = None && sum2 = None && sum3 = None && sum4 = None then None
Вынес

2021-03-18 23:18 UTC, LevonKhazhoyan commented on tests/hometask8Tests/hometask8Tests.fs
> +
Умножение пока не дописал, хотел вместе с транзитивным замыканием сдать, а пока балльчик бы за сумму :)

2021-03-19 07:16 UTC, gsvgit commented on tests/hometask8Tests/hometask8Tests.fs
> +
Ах вот оно что)

2021-03-19 07:19 UTC, gsvgit requested changes

2021-03-19 07:19 UTC, gsvgit commented on src/hometask8/QuadTree.fs
> +                    QuadTree.checkForNone (Node(_go v1 v5, _go v2 v6, _go v3 v7, _go v4 v8)) monoid
Получается, что Вы сперва собираете узел, а потом его разбираете, чтобы проверить, не надо ли его заменить. Зачем лишняя работа?

2021-03-19 07:19 UTC, gsvgit commented on src/hometask8/QuadTree.fs
> +        QuadTreeMtx(x.Rows * y.Rows, x.Cols * y.Cols, _go x.Tree)
Чот тут сервер ругается. На мой взгляд, вполне уместно ругается.

2021-03-19 07:19 UTC, gsvgit commented on tests/hometask8Tests/hometask8Tests.fs
> +      Expect.equal
Ну и да. Я уже писал про тестирование матриц. Сделайте ещё и случайные матрицы, пожалуйста.

2021-03-21 11:03 UTC, LevonKhazhoyan commented on src/hometask8/QuadTree.fs
> +                    QuadTree.checkForNone (Node(_go v1 v5, _go v2 v6, _go v3 v7, _go v4 v8)) monoid
Исправил.

2021-03-21 11:03 UTC, LevonKhazhoyan commented on src/hometask8/QuadTree.fs
> +        QuadTreeMtx(x.Rows * y.Rows, x.Cols * y.Cols, _go x.Tree)
Да, поменял приложение на библиотеку

2021-03-21 11:03 UTC, LevonKhazhoyan commented on tests/hometask8Tests/hometask8Tests.fs
> +      Expect.equal
Сделал.

2021-03-22 07:21 UTC, gsvgit approved these changes
Тензорное и сложение сгодятся.

2021-04-29 11:14 UTC, merged