Hometask_2 commit
LevonKhazhoyan/hometasks pull request #2
Opened 2020-09-25 01:35 UTC by LevonKhazhoyan

Hometask_2 commit

2020-09-25 06:25 UTC, gsvgit requested changes
А ещё тесты не обнаружены.

2020-09-25 06:25 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +           Array.init count (fun _ -> ((rnd.Next ())%10000))
А зачем Вы ещё на 10000 делите?

2020-09-25 06:25 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +   let Subtask_3 (random_array: int array) amount_of_elements maximum =
Вообще говоря, массив не обязан быть случайным в данном случае. У Вас есть просто функция, принимающая массив. Просто Вы её иногда запускаете на случайном. А иногда нет. Это я, если что, к названию переменных придираюсь.

2020-09-25 06:25 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +       printf "Индексы элементов массива, не больших, чем заданное число: "
А что это за печать? Если я правильно понимаю, то сами индексы тут не печатаются. Зачем тогда двоеточие?

2020-09-25 06:25 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +               j <- j+1
А почему где-то Вы ставите пробелы вокруг бинарных операций, а где-то нет?

2020-09-25 06:25 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +       random_array.[i] <- random_array.[i] + random_array.[j]
А правда, что индексы всегда не выходят за границы индексов массива?

2020-09-28 07:27 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +           Array.init count (fun _ -> ((rnd.Next ())%10000))
Да, я уже чуть больше разобрался и понял, что так лучше не делать. А на начальном этапе я думал что лучше уменьшу числа чтобы массив лучше просматривался. Спасибо, исправил.

2020-09-28 07:29 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +   let Subtask_3 (random_array: int array) amount_of_elements maximum =
Спасибо, разобрался. Я как бы ограничил ввод только случайным массивом, понял ошибку.

2020-09-28 07:32 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +               j <- j+1
Исправил! Думал что дедлайн наступает и во многом слабо разобрался, сейчас вроде исправился)

2020-09-28 07:33 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +       random_array.[i] <- random_array.[i] + random_array.[j]
Исправил. Спасибо)

2020-09-28 07:35 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +       printf "Индексы элементов массива, не больших, чем заданное число: "
Я печатал всё ещё до вызова функции. Совсем ужас( Исправил.

2020-09-30 09:51 UTC, gsvgit requested changes
Надо ещё поработать над оформлением кода.

2020-09-30 09:51 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +           Array.init count (fun _ -> ((rnd.Next ())))
А зачем тут столько скобок?

2020-09-30 09:51 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +       let x_plus_x_squared = x_squared + x
Кажется, мы уже успели поговорить о том, что такой стиль наименования не принят в .NET впринципе.

2020-09-30 09:51 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +   let Subtask_3 (xs: int array) maximum =
Такой стиль указания типов не принят в F#/.NET

2020-09-30 09:51 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +          then
Впринципе, блок из одной строки не обязательно переносить на отдельную строку.

2020-09-30 09:51 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +            [||]
А почему, если индексы неправильные, то массив "умерает"?

2020-09-30 09:51 UTC, gsvgit commented on src/hometasks/Hometask_2.fs
> +        else if i = j
есть  ```elif```

2020-10-01 13:29 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +           Array.init count (fun _ -> ((rnd.Next ())))
Убрал.

2020-10-01 13:29 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +       let x_plus_x_squared = x_squared + x
Ой, привычка) исправил

2020-10-01 13:30 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +   let Subtask_3 (xs: int array) maximum =
Исправил.

2020-10-01 13:31 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +          then
Понял, спасибо.

2020-10-01 13:31 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +            [||]
Да, вроде совладал с failwith)

2020-10-01 13:32 UTC, LevonKhazhoyan commented on src/hometasks/Hometask_2.fs
> +        else if i = j
Класс.

2020-10-02 06:59 UTC, gsvgit approved these changes
Ок.

2020-10-05 18:07 UTC, merged