hometask 3
LevonKhazhoyan/hometasks pull request #4
Opened 2020-10-25 22:09 UTC by LevonKhazhoyan

2020-10-26 07:29 UTC, gsvgit requested changes

2020-10-26 07:29 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +        | 1 | 2 -> 1
Для определния чисел Фибоначчи достаточно "вручную" задать два элемента (база). Так что у Вас избыточная конструкция получается.

2020-10-26 07:29 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +            let mutable fibPrevPrev = 0
Опять же, избыточная конструкци.

2020-10-26 07:29 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +            match n with
А здесь нет. Нашли готовое решение?

2020-10-26 07:29 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +            then
А почему Вы иногда однострочные блоки записываете на той же строке, что и ```then``` или ```else``` (например, строка 60), а иногда на новой, как здесь?

2020-10-26 07:29 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +            let mutable x = matrixBinPow matrix factors.[0]
Что-то сложное тут происходит. Это чтобы никто не догадался?

2020-10-26 07:29 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +             let fibMatrix = array2D [ [ 0; 1]; [1; 1] ]
Не совсем аккуртано пробелы расставлены.

2020-10-26 07:29 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +            let mutable fibList = [1; 0]
То, что Вы здесь делаете --- зло. Мутабельный список это само по себе что-то странное. Если действительно хочется поработать со списками, используйте честную рекурсию.

2020-10-26 12:56 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +            let mutable fibList = [1; 0]
Да, можно было сделать почти также как в третьем, я почему-то думал что :: операция тоже только для мутабельных листов, но нет)

2020-10-26 12:56 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +             let fibMatrix = array2D [ [ 0; 1]; [1; 1] ]
Исправил.

2020-10-26 13:00 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +            let mutable x = matrixBinPow matrix factors.[0]
Написал комментариев побольше, надеюсь теперь выглядит лучше :)

2020-10-26 13:01 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +            then
Исправил.

2020-10-26 13:05 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +        | 1 | 2 -> 1
Исправил.

2020-10-26 13:05 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +            let mutable fibPrevPrev = 0
Исправил.

2020-10-26 13:05 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +            match n with
Сложно объяснить
В первом задании я сделал так по глупости.
Во втором задании сделал так, потому что нужно было как-то обозначить fibCurr и как-то не задумывался: писать туда единицу или fibPrev + fibPrevPrev. Увидел разницу.
А в третьем тут даже и не напишешь 2 -> ... сложно будет что-то написать и не сломать) поэтому скорее поля для ошибок не было)
наглупил скорее, не списывал!(разве что с лекции)

2020-10-26 13:07 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +            match n with
Сложно объяснить
В первом задании я сделал так по глупости.
Во втором задании сделал так, потому что нужно было как-то обозначить fibCurr и как-то не задумывался: писать туда единицу или fibPrev + fibPrevPrev. Увидел разницу.
А в третьем тут даже и не напишешь 2 -> ... сложно будет что-то написать и не сломать) поэтому скорее поля для ошибок не было)
наглупил скорее, не списывал!(разве что с лекции)

2020-11-03 06:10 UTC, gsvgit requested changes
Пожалуста, используйте то, что я на парах рассказывал. Постарайтесь сделать код аккуратнее.

2020-11-03 06:10 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +            let mutable x = matrixBinPow matrix factors.[0]
Допустим. Хотя всё ещё выглядит как переусложнение. Не надо так. Чем проще код, тем легче с ним работать. Не надо без нужды усложнять решение.

2020-11-03 06:10 UTC, gsvgit commented on src/hometasks/Hometask3.fs
> +        loop 0 1 (n+1)
И снова пробелы)

2020-11-03 06:10 UTC, gsvgit commented on src/hometasks/Main.fs
>                  printf "Enter the number: "
А-а-а-а!!!! Пожалуйста, постарайтесь использовать то, что я на парах рассказывал.

2020-11-08 21:37 UTC, LevonKhazhoyan commented on src/hometasks/Hometask3.fs
> +        loop 0 1 (n+1)
Исправил.

2020-11-08 21:37 UTC, LevonKhazhoyan commented on src/hometasks/Main.fs
>                  printf "Enter the number: "
Сделал.

2020-11-09 06:59 UTC, gsvgit requested changes
Над оформлением кода ещё надо поработать.

2020-11-09 06:59 UTC, gsvgit commented on src/hometasks/Main.fs
> +                let n = results.GetResult (Subtask1_2)
Что-то Вы написали, что исправили, а общий код так и не выделен. Странно.

2020-11-09 08:15 UTC, LevonKhazhoyan commented on src/hometasks/Main.fs
> +                let n = results.GetResult (Subtask1_2)
Что-то сделал не так, и у меня не запушилось(

2020-11-09 08:19 UTC, gsvgit approved these changes
Ок.

2020-11-09 19:40 UTC, merged