hometask 4
LevonKhazhoyan/hometasks pull request #6
Opened 2020-11-11 21:52 UTC by LevonKhazhoyan

2020-11-12 11:58 UTC, gsvgit requested changes
В основном с оформлением кода проблемы.

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/Main.fs
> +            let result = f1 (f2 (input))
Лишние скобки.

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/Main.fs
> +            let input = Console.ReadLine () |> string
Что-то мне подсказывате, что этот метод должен сразу строку без дополнительных конвертаций возвращать.

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/Main.fs
> +        elif results.Contains Pack32Into64 then
Сурово. Но при таком подходе ```then```лучше переносить на новую строку.

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/hometask4.fs
> +        let lines = System.IO.File.ReadAllLines file
Угу. То есть map Вы как бы знаете, но тут не смогли им воспользоваться?

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/hometask4.fs
> +    let bubbleSortArray (xs: array<int>) =
А давайте всё же не писать типы там, где в этом нет необходимости.

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/hometask4.fs
> +                if first > second then
И опять форматироване.

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/hometask4.fs
> +            then
А здесь другое и, кстати, более правильное.

2020-11-12 11:58 UTC, gsvgit commented on src/hometask4/hometask4.fs
> +    let quickSortListWithFilters (xs: list<int>) =
А это кто за зверь такой?

2020-11-13 08:47 UTC, LevonKhazhoyan commented on src/hometask4/Main.fs
> +            let result = f1 (f2 (input))
Исправил.

2020-11-13 08:47 UTC, LevonKhazhoyan commented on src/hometask4/Main.fs
> +            let input = Console.ReadLine () |> string
Исправил.

2020-11-13 08:47 UTC, LevonKhazhoyan commented on src/hometask4/Main.fs
> +        elif results.Contains Pack32Into64 then
Исправил.

2020-11-13 08:47 UTC, LevonKhazhoyan commented on src/hometask4/hometask4.fs
> +    let bubbleSortArray (xs: array<int>) =
Исправил :)

2020-11-13 08:48 UTC, LevonKhazhoyan commented on src/hometask4/hometask4.fs
> +                if first > second then
Забыл следить за этим, исправил.

2020-11-13 08:48 UTC, LevonKhazhoyan commented on src/hometask4/hometask4.fs
> +            then
Исправил.

2020-11-13 09:14 UTC, LevonKhazhoyan commented on src/hometask4/hometask4.fs
> +    let quickSortListWithFilters (xs: list<int>) =
Сначала написал весь квик сорт по фильтрам, но потом подумал честно и выгодно ли это и решил что на массивах не слишком выгоден(так как можно сделать быстрее довольно легко). На списках вроде как хорош, но не уверен честен ли такой мини "partition". Поэтому отправил вам оба)

2020-11-13 10:01 UTC, LevonKhazhoyan commented on src/hometask4/hometask4.fs
> +        let lines = System.IO.File.ReadAllLines file
Вы мне помогли) я понимал по ошибке что фшарп не поймёт типы, но как-то я не умело ему помогал(

2020-11-19 11:15 UTC, gsvgit requested changes
оформление и типы всё ещё страдают. И force push --- очень плохая затея. Кажется, я даже говорил об этом на парах.

2020-11-19 11:15 UTC, gsvgit commented on src/hometask4/hometask4.fs
> +    let packing32To64 (a: int32, b: int32) =
Павда ли, что в функциях распаковки-запаковки везде нужны указания типов?

2020-11-19 11:15 UTC, gsvgit commented on src/hometask4/Main.fs
> +        elif results.Contains Unpack64Into32 then
А почему до какого-то момента поменяли форматирование, а потом опять старое?

2020-11-19 17:39 UTC, LevonKhazhoyan commented on src/hometask4/Main.fs
> +        elif results.Contains Unpack64Into32 then
Исправил.

2020-11-19 17:39 UTC, LevonKhazhoyan commented on src/hometask4/hometask4.fs
> +    let packing32To64 (a: int32, b: int32) =
Исправил.

2020-11-20 08:29 UTC, gsvgit commented
Да, что-то сборка у Вас разъехалась. Чтобы такого не было, запускайте у себя локально скрипт.

2020-11-20 10:19 UTC, LevonKhazhoyan commented on src/hometask4/hometask4.fs
> +    let packing32To64 (a: int32, b: int32) =
Ничего я не исправил на тот момент) почему-то я думал что раз вы спросили правда ли, что можно убрать, то это значит что можно везде убрать и всё будет хорошо) но нет, в main возникли проблемы. Вчера увидел, что не забилдилось, но надеялся т.к. я не запросил ревью - вы не увидите)  Во всех местах не получилось убрать указания типов, но сделал что мог.

2020-11-21 08:02 UTC, gsvgit approved these changes

2020-11-21 16:04 UTC, merged