hometask6
LevonKhazhoyan/hometasks pull request #7
Opened 2020-12-13 15:26 UTC by LevonKhazhoyan

2020-12-14 06:52 UTC, gsvgit requested changes

2020-12-14 06:52 UTC, gsvgit commented on src/hometask6/hometask6.fs
> +                    for j in matrix2.Coordinates do
Правда ли, что некоторые координаты не будут повторяться в результирующем списке?

2020-12-14 06:52 UTC, gsvgit commented on src/hometask6/hometask6.fs
> +                    for j in matrix2.Coordinates do
Например, умножим 
1 1
1 1
на
1 1 
1 1

Что получится?

2020-12-14 12:42 UTC, LevonKhazhoyan commented on src/hometask6/hometask6.fs
> +                    for j in matrix2.Coordinates do
ой, будут в два раза больше координат, точно! исправил)

2020-12-16 11:08 UTC, gsvgit approved these changes

2020-12-16 11:09 UTC, merged