hometask7
LevonKhazhoyan/hometasks pull request #8
Opened 2021-02-09 15:35 UTC by LevonKhazhoyan

2021-02-11 06:59 UTC, gsvgit requested changes
У Вас какая-то каша с форматированием. Разберитесь, пожалуйста.

2021-02-11 06:59 UTC, gsvgit commented on src/hometask7/MyList.fs
> +
Почему у Вас какое-то рандомное колическтво строк между функциями?

2021-02-11 06:59 UTC, gsvgit commented on src/hometask7/MyList.fs
> +            | One x -> Cons(x, l2)
match как-нибудь однообразно форматируйте, пожалуйста.

2021-02-11 06:59 UTC, gsvgit commented on src/hometask7/MyList.fs
> +        concat str1 str2
И с отсупами тоже разберитесь.

2021-02-11 06:59 UTC, gsvgit commented on src/hometask7/MyList.fs
> +        then
И с форматированием if-ов

2021-02-11 06:59 UTC, gsvgit commented on src/hometask7/MyList.fs
> +        let rec go lst myLst =
Мне кажется, Вы тут ещё раз fold написали.

2021-02-13 14:42 UTC, gsvgit requested changes

2021-02-13 14:42 UTC, gsvgit commented on src/hometask7/MyList.fs
> +    | h when h.Length = 1 -> One l.[0]
Думается, 
```
h::[] 
```
Должно работать.

2021-02-13 14:42 UTC, gsvgit commented on src/hometask7/MyList.fs
> +        if a = len xs then xs
Либо всё в одну строку, либо в 3.
```
if cond then a else b

if cond
then a
else b
```

2021-02-13 14:42 UTC, gsvgit commented on src/hometask7/MyList.fs
> +        fold (fun list x -> list @ [x]) [] myLst
Либо добавлять в начало, а потом ревёрснуть, так как добавлять в конец дорого.

2021-02-13 17:35 UTC, gsvgit requested changes
Осталось совсем немного побороть форматирование.

2021-02-13 17:35 UTC, gsvgit commented on src/hometask7/MyList.fs
> +        | One x -> Cons (x, l2)
А почему отступы снова разъехались?

2021-02-13 17:46 UTC, LevonKhazhoyan commented on src/hometask7/MyList.fs
> +        | One x -> Cons (x, l2)
Очень невнимательный, извините( сессия и отдых дают о себе знать.

2021-02-13 17:48 UTC, gsvgit commented on src/hometask7/MyList.fs
> +        | One x -> Cons (x, l2)
Особенно отдых, да )

2021-02-13 17:49 UTC, LevonKhazhoyan commented on src/hometask7/MyList.fs
> +        | One x -> Cons (x, l2)
Я о том что математика была одна на экзаменах, теперь вот пытаюсь возвращаться

2021-02-15 09:56 UTC, gsvgit approved these changes
Выстрадали) Осталось целый 1 балл где-то добыть.

2021-02-15 15:49 UTC, merged